name: chimeric-detective-minimal
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Python
  - python>=3.8
  
  # Essential external tools
  - bwa>=0.7.17
  - minimap2>=2.20
  - samtools>=1.15
  
  # Core Python packages
  - biopython>=1.79
  - pysam>=0.19.0
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - plotly>=5.0.0
  - click>=8.0.0
  - tqdm>=4.62.0
  - jinja2>=3.0.0
  
  # Pip for package installation
  - pip