name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y bwa minimap2 samtools

    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install bwa minimap2 samtools

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Install pytest first
        pip install -e .

    - name: Test basic imports
      run: |
        python -c "import chimeric_detective; print('✅ Package import successful')"
        python -c "from chimeric_detective.detector import ChimeraDetector; print('✅ Detector import successful')"
        python -c "from chimeric_detective.cli import main; print('✅ CLI import successful')"

    - name: Test CLI commands
      run: |
        chimeric_detective --help
        chimeric_detective --version

    - name: Run import tests
      run: |
        # Run tests with explicit python path
        python -m pytest tests/test_imports.py -v

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        twine check dist/*